language: cpp
compiler: clang
script:
  - pushd ./outliers
  - make
  - gcov demo.cpp
  - gcov methods.cpp
  - gcov outlier-detection.cpp
  - popd
after_success:
  - bash <(curl -s https://codecov.io/bash)
